apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  REDIS_HOST: redis.default.svc.cluster.local
  REDIS_PORT: "6379"
  POSTGRES_HOST: postgres.default.svc.cluster.local
  POSTGRES_PORT: "5432"