apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voteapp-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: voteapp.ddns.net
    http:
      paths:
      - path: /vote
        pathType: Prefix
        backend:
          service:
            name: voteapp-service
            port:
              number: 30001
      - path: /result
        pathType: Prefix
        backend:
          service:
            name: resultapp-service
            port:
              number: 30002