apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-result-ingress
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - path: /vote
        pathType: Prefix
        backend:
          service:
            name: vote-servic
            port:
              number: 5000
      - path: /result
        pathType: Prefix
        backend:
          service:
            name: result-servic
            port:
              number: 5001